name: WGExtraFlags
description: Adds more flags to WorldGuard to help manage your server easily!
version: ${project.version}
api-version: 1.21

author: isokissa3
website: https://joniaromaa.fi

depend: [ WorldGuard ]
softdepend: ['packetevents', 'MythicLib']

main: net.goldtreeservers.worldguardextraflags.WGExtraFlags